---
name: Container Release (Rocky Linux 9)

on:
  push:
    branches:
      - main
  schedule:
    # At 23:00 on Sunday.
    - cron: "0 23 * * 0"

jobs:
  build-test:
    name: Container Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Build Docker image
        run: docker build .

  build-release:
    name: Container Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dudecalledbro/molecule-rockylinux-9:latest
